### ISSUE TITLE
Stable version TODO

### ISSUE THREAD

**Issue by maxnordlund** [maxnordlund/decorators#1]
Before I can release this I need to fix a few things. Firstly I need tests, and for that I'll use Mocha/Chai/Sinon, and hopefully setup some sort of browser testing. I don't think I can automate the deployment to npm completely, since I want _both_ *nix and windows CI.

After digging around a bit I might get away with Saucelabs, and [karma](https://karma-runner.github.io/)
- [ ] Write tests
  - [ ] Unit tests for all decorators.
  - [ ] Maybe some sort of integration test/examples. Doctest if it exists would be sweet.
  - [ ] ESLint config, and hopefully integrate this into the test suite.
- [ ] Setup CI/CD
  - [ ] Circle/Semaphore/Travis/Drone
  - [ ] Appveyor
  - [ ] Saucelabs/BrowserStack
  - [ ] CodeClimate
  - [ ] Coveralls (because CodeClimate dosen't support parallelism)
  - [ ] Hound
  - [ ] InchCI
- [ ] Publish it on [npm](https://npmjs.org)
  - [ ] Create a `package.json`
  - [ ] Register it on [npm](https://npmjs.org)
- [ ] Publish it on bower
  - [ ] Create a `bower.json`
  - [ ] Register it on [bower.io](http://bower.io/) if needed

**Comment by maxnordlund** [comment]
Useful links:
- https://github.com/princed/karma-chai-plugins
- https://github.com/karma-runner/karma-sauce-launcher
- https://github.com/babel/karma-babel-preprocessor
- https://github.com/caitp/karma-coveralls (https://github.com/nickmerwin/node-coveralls)
- https://github.com/bltavares/karma-notification-reporter
